### ISSUE TITLE
Cannot write to /usr/share/PancakePainter/resources/app/settings.json

### ISSUE THREAD

**Issue by xsuchy** [PancakeBot/PancakeCreator#98]
When running PancakePainter on Fedora 26 I get following traceback:
```

$ PancakePainter 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/usr/share/PancakePainter/resources/app/settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/usr/share/PancakePainter/resources/app/node_modules/fs-plus/lib/fs-plus.js:288:17)
    at Object.app.settings.save (/usr/share/PancakePainter/resources/app/src/main.js:108:10)
    at Object.app.settings.load (/usr/share/PancakePainter/resources/app/src/main.js:125:12)
    at settingsInit (/usr/share/PancakePainter/resources/app/src/main.js:133:16)
    at start (/usr/share/PancakePainter/resources/app/src/main.js:33:3)
    at Object.<anonymous> (/usr/share/PancakePainter/resources/app/src/main.js:216:1)
```
This is because the 
```
$ ls -l /usr/share/PancakePainter/resources/app/settings.json
-rw-r--r--. 1 root root 363 21. úno  2017 /usr/share/PancakePainter/resources/app/settings.json
```
This can be workarounded by chmod 666 on that file. However correct way would be to just read this config for the defaults and put overrides to `~/.config/PancakePainter.json` and write any chages there.

**Comment by techninja** [comment]
Closing as PR merged to master, thanks for the contributions!
